
export const CALCULATE_BUYBACK_PRICE_REQUEST = 'CALCULATE_BUYBACK_PRICE_REQUEST';
export const CALCULATE_BUYBACK_PRICE_SUCCESS = 'CALCULATE_BUYBACK_PRICE_SUCCESS';
export const CALCULATE_BUYBACK_PRICE_FAILURE = 'CALCULATE_BUYBACK_PRICE_FAILURE';

export const CALCULATE_BUYBACK_PRICE_OUT_REQUEST = 'CALCULATE_BUYBACK_PRICE_OUT_REQUEST';
export const CALCULATE_BUYBACK_PRICE_OUT_SUCCESS = 'CALCULATE_BUYBACK_PRICE_OUT_SUCCESS';
export const CALCULATE_BUYBACK_PRICE_OUT_FAILURE = 'CALCULATE_BUYBACK_PRICE_OUT_FAILURE';

