

export const UPDATE_STOCK = 'UPDATE_STOCK';

export const GET_ALL_COMPONENT_REQUEST = 'GET_ALL_COMPONENT_REQUEST';
export const GET_ALL_COMPONENT_SUCCESS = 'GET_ALL_COMPONENT_SUCCESS';
export const GET_ALL_COMPONENT_FAILURE = 'GET_ALL_COMPONENT_FAILURE';

export const CREATE_COMPONENT_REQUEST = 'CREATE_COMPONENT_REQUEST';
export const CREATE_COMPONENT_SUCCESS = 'CREATE_COMPONENT_SUCCESS';
export const CREATE_COMPONENT_FAILURE = 'CREATE_COMPONENT_FAILURE';

export const GET_COMPONENT_REQUEST = 'GET_COMPONENT_REQUEST';
export const GET_COMPONENT_SUCCESS = 'GET_COMPONENT_SUCCESS';
export const GET_COMPONENT_FAILURE = 'GET_COMPONENT_FAILURE';

export const UPDATE_COMPONENT_REQUEST = 'UPDATE_COMPONENT_REQUEST';
export const UPDATE_COMPONENT_SUCCESS = 'UPDATE_COMPONENT_SUCCESS';
export const UPDATE_COMPONENT_FAILURE = 'UPDATE_COMPONENT_FAILURE';