// actionTypes.js

export const CREATE_AREA_REQUEST = "CREATE_AREA_REQUEST";
export const CREATE_AREA_SUCCESS = "CREATE_AREA_SUCCESS";
export const CREATE_AREA_FAILURE = "CREATE_AREA_FAILURE";

export const UPDATE_AREA_REQUEST = "UPDATE_AREA_REQUEST";
export const UPDATE_AREA_SUCCESS = "UPDATE_AREA_SUCCESS";
export const UPDATE_AREA_FAILURE = "UPDATE_AREA_FAILURE";

export const GET_ALL_AREA_REQUEST = "GET_ALL_AREA_REQUEST";
export const GET_ALL_AREA_SUCCESS = "GET_ALL_AREA_SUCCESS";
export const GET_ALL_AREA_FAILURE = "GET_ALL_AREA_FAILURE";

export const DELETE_AREA_REQUEST = "DELETE_AREA_REQUEST";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCESS";
export const DELETE_AREA_FAILURE = "DELETE_AREA_FAILURE";

export const GET_AREA_BY_ID_REQUEST = "GET_AREA_BY_ID_REQUEST";
export const GET_AREA_BY_ID_SUCCESS = "GET_AREA_BY_ID_SUCCESS";
export const GET_AREA_BY_ID_FAILURE = "GET_AREA_BY_ID_FAILURE";


export const GET_AREA_BY_USER_ID_REQUEST = "GET_AREA_BY_USER_ID_REQUEST";
export const GET_AREA_BY_USER_ID_SUCCESS = "GET_AREA_BY_USER_ID_SUCCESS";
export const GET_AREA_BY_USER_ID_FAILURE = "GET_AREA_BY_USER_ID_FAILURE";


export const UPDATE_AREA_STATUS_REQUEST = "UPDATE_AREA_STATUS_REQUEST";
export const UPDATE_AREA_STATUS_SUCCESS = "UPDATE_AREA_STATUS_SUCCESS";
export const UPDATE_AREA_STATUS_FAILURE = "UPDATE_AREA_STATUS_FAILURE";

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

export const GET_AREA_EVENTS_REQUEST = "GET_AREA_EVENTS_REQUEST";
export const GET_AREA_EVENTS_SUCCESS = "GET_AREA_EVENTS_SUCCESS";
export const GET_AREA_EVENTS_FAILURE = "GET_AREA_EVENTS_FAILURE";

// export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
// export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
// export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

// export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
// export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
// export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";







