
export const CREATE_BUYBACK_REQUEST = 'CREATE_BUYBACK_REQUEST';
export const CREATE_BUYBACK_SUCCESS = 'CREATE_BUYBACK_SUCCESS';
export const CREATE_BUYBACK_FAILURE = 'CREATE_BUYBACK_FAILURE';

export const CREATE_BUYBACK_OUT_REQUEST = 'CREATE_BUYBACK_OUT_REQUEST';
export const CREATE_BUYBACK_OUT_SUCCESS = 'CREATE_BUYBACK_OUT_SUCCESS';
export const CREATE_BUYBACK_OUT_FAILURE = 'CREATE_BUYBACK_OUT_FAILURE';

export const GET_ALL_BUYBACK_REQUEST = 'GET_ALL_BUYBACK_REQUEST';
export const GET_ALL_BUYBACK_SUCCESS = 'GET_ALL_BUYBACK_SUCCESS';
export const GET_ALL_BUYBACK_FAILURE = 'GET_ALL_BUYBACK_FAILURE';
