
export const GET_WARRANTYS_REQUEST = 'GET_WARRANTYS_REQUEST';
export const GET_WARRANTYS_SUCCESS = 'GET_WARRANTYS_SUCCESS';
export const GET_WARRANTYS_FAILURE = 'GET_WARRANTYS_FAILURE';

export const GET_WARRANTY_BY_ORDER_ID_REQUEST = 'GET_WARRANTY_BY_ORDER_ID_REQUEST';
export const GET_WARRANTY_BY_ORDER_ID_SUCCESS = 'GET_WARRANTY_BY_ORDER_ID_SUCCESS';
export const GET_WARRANTY_BY_ORDER_ID_FAILURE = 'GET_WARRANTY_BY_ORDER_ID_FAILURE';

export const GET_WARRANTY_BY_ID_REQUEST = 'GET_WARRANTY_BY_ID_REQUEST';
export const GET_WARRANTY_BY_ID_SUCCESS = 'GET_WARRANTY_BY_ID_SUCCESS';
export const GET_WARRANTY_BY_ID_FAILURE = 'GET_WARRANTY_BY_ID_FAILURE';