// actionTypes.js
//Tổng
export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';

// theo quầy
export const GET_DASHBOARD_AREA_REQUEST = 'GET_DASHBOARD_AREA_REQUEST';
export const GET_DASHBOARD_AREA_SUCCESS = 'GET_DASHBOARD_AREA_SUCCESS';
export const GET_DASHBOARD_AREA_FAILURE = 'GET_DASHBOARD_AREA_FAILURE';
//từng quầy
export const GET_DASHBOARD_AREAS_REQUEST = 'GET_DASHBOARD_AREAS_REQUEST';
export const GET_DASHBOARD_AREAS_SUCCESS = 'GET_DASHBOARD_AREAS_SUCCESS';
export const GET_DASHBOARD_AREAS_FAILURE = 'GET_DASHBOARD_AREAS_FAILURE';


export const GET_DASHBOARD_BUYBACK_REQUEST = 'GET_DASHBOARD_BUYBACK_REQUEST';
export const GET_DASHBOARD_BUYBACK_SUCCESS = 'GET_DASHBOARD_BUYBACK_SUCCESS';
export const GET_DASHBOARD_BUYBACK_FAILURE = 'GET_DASHBOARD_BUYBACK_FAILURE';

// theo quầy
export const GET_DASHBOARD_BUYBACK_AREA_REQUEST = 'GET_DASHBOARD_BUYBACK_AREA_REQUEST';
export const GET_DASHBOARD_BUYBACK_AREA_SUCCESS = 'GET_DASHBOARD_BUYBACK_AREA_SUCCESS';
export const GET_DASHBOARD_BUYBACK_AREA_FAILURE = 'GET_DASHBOARD_BUYBACK_AREA_FAILURE';
//từng quầy
export const GET_DASHBOARD_BUYBACK_AREAS_REQUEST = 'GET_DASHBOARD_BUYBACK_AREAS_REQUEST';
export const GET_DASHBOARD_BUYBACK_AREAS_SUCCESS = 'GET_DASHBOARD_BUYBACK_AREAS_SUCCESS';
export const GET_DASHBOARD_BUYBACK_AREAS_FAILURE = 'GET_DASHBOARD_BUYBACK_AREAS_FAILURE';

